### ISSUE TITLE
include helm chart/release (app) info if available

### ISSUE THREAD

**Issue by bergerx** [bergerx/kubectl-status#174]
It could be helpful for operators to see which helm chart/release a resource is created as a result of.

Here is some metadata added by Helm, these are mostly conventions but would still be helpful for the majority of the users if we can have these.

```yaml
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    meta.helm.sh/release-name: stable-prometheus-operator
    meta.helm.sh/release-namespace: monitoring
  labels:
    app.kubernetes.io/instance: stable-prometheus-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 7.4.3
    helm.sh/chart: grafana-6.6.3
```

This could be something like this:
```
Deployment/stable-prometheus-operator-grafana -n monitoring, created 5mo ago, gen:2
  Helm release:stable-prometheus-operator chart:grafana-6.6.3 
```

Even for non-Helm users, the `app.kubernetes.io/*` labels would still be helpful to identify the application.
