### ISSUE TITLE
Installation fails on different platforms?

### ISSUE THREAD

**Issue by bergerx** [bergerx/kubectl-status#341]
![image](https://user-images.githubusercontent.com/45531/193558785-fa2a28e8-c32b-4520-8c03-bc2df01732e3.png)

I asked for more details like `kubectl version -o yaml` and `kubectl krew version`, I will update this once received.

**Comment by kushangbhatt** [comment]
`kubectl version -o yaml`

```
clientVersion:
  buildDate: "2022-07-13T14:21:56Z"
  compiler: gc
  gitCommit: aef86a93758dc3cb2c658dd9657ab4ad4afc21cb
  gitTreeState: clean
  gitVersion: v1.24.3
  goVersion: go1.18.4
  major: "1"
  minor: "24"
  platform: darwin/arm64
kustomizeVersion: v4.5.4
```

`kubectl krew version`

```
OPTION            VALUE
GitTag            v0.4.3
GitCommit         dbfefa5
IndexURI          https://github.com/kubernetes-sigs/krew-index.git
BasePath          /Users/bkushang/.krew
IndexPath         /Users/bkushang/.krew/index/default
InstallPath       /Users/bkushang/.krew/store
BinPath           /Users/bkushang/.krew/bin
DetectedPlatform  darwin/arm64
```
